team page
gdsc-nits-org/nits-hacks-6.0 pull request #16
Opened 2024-01-15 16:01 UTC by rishinhk004

2024-01-15 16:32 UTC, bj-jiwrajka requested changes

2024-01-15 16:32 UTC, bj-jiwrajka commented on src/Pages/TeamPage/Team.jsx
> +                    <img className={styles.logo} src="https://s3-alpha-sig.figma.com/img/1c7f/bbb4/7f72f4cd9c19126b202afe2584ed4b29?Expires=1705881600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=i1aXe
replace the URLs with the cloudinary links used in footer

2024-01-15 16:32 UTC, bj-jiwrajka commented on src/Pages/TeamPage/Team.jsx
> +    ];
make separate json files for faculty, tech team, organisers, etc and use them here

2024-01-15 16:32 UTC, bj-jiwrajka commented on src/Pages/TeamPage/Team.module.scss
> +    padding: 10px 24px;
replace ```px``` by  ```rem/em```

2024-01-15 16:32 UTC, bj-jiwrajka commented on src/Pages/TeamPage/Team.module.scss
> +}
remove the redundant code and try to choose uniform breakpoints, _take reference from other components_

2024-01-16 17:22 UTC, byt3h3ad commented
![image](https://github.com/gdsc-nits-org/nits-hacks-6.0/assets/26319721/c03be0af-92a4-42c8-9570-2884b4358c8c)
github icon looks weird. 


![image](https://github.com/gdsc-nits-org/nits-hacks-6.0/assets/26319721/f283e5d7-0a51-44a5-8a6e-7e4aaee2d0c7)
alignment issue again.

2024-01-17 13:14 UTC, byt3h3ad commented on src/Pages/TeamPage/TeamPage.module.scss
> +  overflow-x: hidden;
this overflow hidden is hampering the functioning of  react-scroll. so either remove this or don't use react-scroll.

2024-01-18 12:09 UTC, merged