Footer
gdsc-nits-org/nits-hacks-6.0 pull request #7
Opened 2024-01-13 10:48 UTC by rishav3110

Maps not working

2024-01-13 13:09 UTC, bj-jiwrajka requested changes

2024-01-13 13:09 UTC, bj-jiwrajka commented on src/components/Footer/Footer.jsx
> +                        <p className={styles.gmail}>nitshack@gmail.com</p>
change the email to ```nitshacks.nits@gmail.com```

2024-01-13 13:09 UTC, bj-jiwrajka commented on src/components/Footer/Footer.jsx
> +                <div className={styles.upper2}>
![image](https://github.com/gdsc-nits-org/nits-hacks-6.0/assets/97835955/3d08e23d-f89e-429a-942a-b1c2113ccaaf)

try to make the changes exactly as given in the design

2024-01-13 17:18 UTC, bj-jiwrajka requested changes

2024-01-13 17:18 UTC, bj-jiwrajka commented on src/components/Footer/Footer.module.scss
> +    gap: 16.194px;
change px to relative units

2024-01-13 17:19 UTC, bj-jiwrajka commented
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> Name 	Status 	Preview 	Updated (UTC)
> **nits-hacks-6-0** 	✅ Ready ([Inspect](https://vercel.com/nitshacks/nits-hacks-6-0/37GgJUaeuMTTMQbCoZKfB5EX3Nom)) 	[Visit Preview](https://nits-hacks-6-0-git-footer-nitshacks.vercel.app) 	Jan 13, 2024 10:48am

![image](https://github.com/gdsc-nits-org/nits-hacks-6.0/assets/97835955/c2066688-7da6-4efe-9c99-5ca5aa320623)

seems too big, fix it!

2024-01-13 19:29 UTC, byt3h3ad commented
(merge conflicts resolve karna)

2024-01-14 05:04 UTC, bj-jiwrajka requested changes

2024-01-14 05:04 UTC, bj-jiwrajka commented on src/components/Footer/Footer.jsx
> +						<p className={styles.gmail}>nitshacks.nits@gmail.com</p>
make it clickable, use ```mail:to```

2024-01-14 11:39 UTC, bj-jiwrajka requested changes

2024-01-14 11:39 UTC, bj-jiwrajka commented on src/components/Footer/Footer.jsx
> +	return (
Format the code and add links to social handles

2024-01-14 11:40 UTC, bj-jiwrajka commented on src/components/Footer/Footer.module.scss
> +    gap: 16.194px;
fix this too :)

2024-01-15 14:24 UTC, merged