Design of Event page
gdsc-nits-org/nits-hacks-6.0 pull request #8
Opened 2024-01-14 04:43 UTC by zordican

ADD: Event page design and Made it responsive

2024-01-14 04:57 UTC, bj-jiwrajka commented
> ADD: Event page design and Made it responsive

Design:

![image](https://github.com/gdsc-nits-org/nits-hacks-6.0/assets/97835955/594003e0-088e-4667-8182-1b74f67c8e8d)

Yours:

![image](https://github.com/gdsc-nits-org/nits-hacks-6.0/assets/97835955/460aa0eb-f7ec-4f77-a61d-1056a043fb5f)

fix this @zordican

2024-01-14 05:01 UTC, bj-jiwrajka commented
> ADD: Event page design and Made it responsive

Fix this for smaller devices:

![image](https://github.com/gdsc-nits-org/nits-hacks-6.0/assets/97835955/85ad1db6-aa87-49d9-a6e8-3d436b660570)

2024-01-14 06:18 UTC, byt3h3ad requested changes

2024-01-14 06:18 UTC, byt3h3ad commented on public/Font/PixeloidSans-Bold.ttf
already present in dev

2024-01-14 06:18 UTC, byt3h3ad commented on public/Font/PixeloidSans.ttf
already present in dev

2024-01-14 06:18 UTC, byt3h3ad commented on src/Pages/Home/EventPage/EventPage.module.scss
> +    url("../../../../public/Font/PixeloidSans.ttf") format("truetype");
change to `/fonts/[path].` files in public directory are served at the root path.

2024-01-14 06:18 UTC, byt3h3ad commented on src/Pages/Home/EventPage/EventPage.module.scss
> +    url("../../../../public/Font/PixeloidSans-Bold.ttf") format("truetype");
change to `/fonts/[path]`. files in public directory are served at the root path.

2024-01-14 09:32 UTC, bj-jiwrajka requested changes

2024-01-14 09:32 UTC, bj-jiwrajka commented on src/App.jsx
> -				<Route exact path="/Event" element={<EventPage />} />
add the route to event page

2024-01-14 09:43 UTC, bj-jiwrajka requested changes

2024-01-14 09:43 UTC, bj-jiwrajka commented on src/Pages/Home/EventPage/EventPage.module.scss
> +            color: #C7FFF2;
add the color in ```index.scss``` file

2024-01-15 04:09 UTC, bj-jiwrajka commented
@zordican move the ```EventPage``` folder outside the ```Home``` page

2024-01-15 04:47 UTC, bj-jiwrajka requested changes

2024-01-15 04:47 UTC, bj-jiwrajka commented on src/App.jsx
> +		<>
your Event Page is displaying the content of HomePage too, fix this

2024-01-15 04:59 UTC, bj-jiwrajka requested changes

2024-01-15 04:59 UTC, bj-jiwrajka commented on src/Pages/EventPage/EventPage.module.scss
> +    height: 100vh;
why is it fixed to 100vh? (_if needed, use min-height)_

2024-01-15 04:59 UTC, bj-jiwrajka commented on src/Pages/EventPage/EventPage.module.scss
> +        height: 100vh;
same again :)

due to this, the buttons at the bottom are not visible

2024-01-15 19:08 UTC, byt3h3ad commented
merging.

2024-01-15 20:39 UTC, merged